name: Apigee-POC

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        description: Enviornment to deploy
        options: 
        - eval
        - test
      name1:
        type: choice
        required: true
        description: Api to deploy
        options: 
        - Mock-v1
        - security
      job-name:
        type: choice
        description: 'Job id'
        required: true
        options: 
        - Deploy
        - Unit Test
        - Rollback		
jobs:
  Rollback:
    name: Rollback
    if: ${{ github.event.inputs.job-name == 'Rollback' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: 'projects/762356276584/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 's1-679@absolute-gantry-344218.iam.gserviceaccount.com'
      - name: Fetch Current Revision
        id: fetch
        run: "echo \"::set-output name=current-revision::$(curl -H \"Authorization: Bearer ${{steps.auth.outputs.access_token}}\" \"https://apigee.googleapis.com/v1/organizations/absolute-gantry-344218/apis/${{github.event.inputs.name1}}/deployments\" | jq -r '.deployments[] | select(.environment==\"${{github.event.inputs.name}}\") | .revision' )\""
      - name: Fetch Last Revision
        id: GetRev
        run: "echo \"::set-output name=previous-revision::$((${{steps.fetch.outputs.current-revision}}-1))\""
      - name: test
        run: echo ${{steps.GetRev.outputs.previous-revision}}
