name: Apigee-POC

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        description: Enviornment to deploy
        options: 
        - eval
        - test
      name1:
        type: choice
        required: true
        description: Api to deploy
        options: 
        - Mock-v1
        - security
      RevisionToDeploy:
        description:  Stable Revision for Rollback
      
      job-name:
        type: choice
        description: 'Job id'
        required: true
        options: 
        - Deploy
        - Unit Test
        - Rollback
        - Undeploy
jobs:
 build:
    name: "Deploy"
    if: ${{ github.event.inputs.job-name == 'Deploy' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: 'projects/762356276584/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 's1-679@absolute-gantry-344218.iam.gserviceaccount.com'

    # - name: Create API bundle
     #   run: zip -r proxy.zip apiproxy
      #- name: Upload API Proxy Bundle
       # id: upload
        #run: "echo \"::set-output name=apigee-revision::$(curl --fail -X POST -H \"Content-Type: multipart/form-data\" -H \"Authorization: Bearer ${{steps.auth.outputs.access_token}}\" -F \"file=@proxy.zip\" \"https://apigee.googleapis.com/v1/organizations/absolute-gantry-344218/apis?action=import&name=hello-world\" --silent | jq --raw-output .revision)\""
      #- name: Deploy Revision
       # run: "curl --fail -X POST -H \"Authorization: Bearer ${{steps.auth.outputs.access_token}}\" \"https://apigee.googleapis.com/v1/organizations/absolute-gantry-344218/environments/eval/apis/hello-world/revisions/${{steps.upload.outputs.apigee-revision}}/deployments?override=true\""
    
      - name: "maven"
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
      - name: Build with maven  
        working-directory: ${{github.event.inputs.name1}}/
        run: mvn  install -P${{github.event.inputs.name}} -Dbearer=${{steps.auth.outputs.access_token}} -Dapigee.config.options=update 
 Rollback:
    name: Rollback
    if: ${{ github.event.inputs.job-name == 'Rollback' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: 'projects/762356276584/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 's1-679@absolute-gantry-344218.iam.gserviceaccount.com'
      - name: Fetch Current Revision
        id: fetch
        run: "echo \"::set-output name=current-revision::$(curl -H \"Authorization: Bearer ${{steps.auth.outputs.access_token}}\" \"https://apigee.googleapis.com/v1/organizations/absolute-gantry-344218/apis/${{github.event.inputs.name1}}/deployments\" | jq -r '.deployments[] | select(.environment==\"${{github.event.inputs.name}}\") | .revision' )\""
      - name: Undeploy Deployed Revision 
        run: |
          curl -X DELETE --header "Authorization: Bearer ${{steps.auth.outputs.access_token}}" "https://apigee.googleapis.com/v1/organizations/absolute-gantry-344218/environments/${{github.event.inputs.name}}/apis/${{github.event.inputs.name1}}/revisions/${{steps.fetch.outputs.current-revision}}/deployments"
                    
          curl -X POST --header "Content-Type: application/x-www-form-urlencoded" --header "Authorization: Bearer ${{steps.auth.outputs.access_token}}" "https://apigee.googleapis.com/v1/organizations/absolute-gantry-344218/environments/${{github.event.inputs.name}}/apis/${{github.event.inputs.name1}}/revisions/${{github.event.inputs.RevisionToDeploy}}/deployments"
          
 Undeploy:
    name: Undeploy 
    if: ${{ github.event.inputs.job-name == 'Undeploy' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: 'projects/762356276584/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 's1-679@absolute-gantry-344218.iam.gserviceaccount.com'
      - name: Fetch Current Revision
        id: fetch
        run: "echo \"::set-output name=current-revision::$(curl -H \"Authorization: Bearer ${{steps.auth.outputs.access_token}}\" \"https://apigee.googleapis.com/v1/organizations/absolute-gantry-344218/apis/${{github.event.inputs.name1}}/deployments\" | jq -r '.deployments[] | select(.environment==\"${{github.event.inputs.name}}\") | .revision' )\""
      - name: Undeploy Deployed Revision 
        run: |
          curl -X DELETE --header "Authorization: Bearer ${{steps.auth.outputs.access_token}}" "https://apigee.googleapis.com/v1/organizations/absolute-gantry-344218/environments/${{github.event.inputs.name}}/apis/${{github.event.inputs.name1}}/revisions/${{steps.fetch.outputs.current-revision}}/deployments"
        
     
     
